.TH "charPack" 3 "Sat Apr 16 2011" "Version 1.0" "ERTS - Firebrd Swzz Knife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
charPack \- 
.PP
internal struct to recieve data from zigbee  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBdata\fP"
.br
.ti -1c
.RI "struct charpack * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
internal struct to recieve data from zigbee 

internal struct used to recieve data from zigbee. uses linked list structure 
.SH "Field Documentation"
.PP 
.SS "char \fBdata\fP"
.SS "struct charpack* \fBnext\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ERTS - Firebrd Swzz Knife from the source code.
